
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



    driver-class-name=com:
      mysql:
        jdbc:
          Driver:
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com.example.webhomework.mapper/*.xml